[package]
name = "rox-cli"
authors = ["Thomas La Piana"]
description = "A YAML-Defined CLI for Dev Tools"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/ThomasLaPiana/rox"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "rox"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["string"] }
colored = "2.0.4"
semver = "1.0.18"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
