[package]
name = "rox"
authors = ["Thomas La Piana"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.2", features = ["string"] }
colored = "2.0.4"
semver = "1.0.18"
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
