name: CI

on:
  push:
    branches: [main]
    paths-ignore: [README.md]

  pull_request:
    branches: [main]
    paths-ignore: [README.md]

jobs:
  Suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          rustup update
          rustup component add clippy

      - name: Build
        run: cargo build --release

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test
