name: CI

on:
  push:
    branches: [main]
    paths-ignore: [README.md]
    tags: ["*"]

  pull_request:
    branches: [main]
    paths-ignore: [README.md]

jobs:
  Suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          rustup update
          rustup component add clippy
          cargo install cargo-audit
          cargo install cargo-nextest
          cargo install cargo-watch

      - name: Build
        run: cargo build

      - name: Format
        run: cargo run task fmt

      - name: Lint
        run: cargo run task clippy-ci

      - name: Security Audit
        run: cargo audit

      - name: Test
        run: cargo run task test
